// Cloudflare Worker: stores each browser's favourite event ids in KV and
// serves a personal, always-up-to-date .ics feed at /fav.ics?u=<id>.
//
// Routes:
//   POST /save?u=<uid>   body {favs:[id...], bought:[id...]}  -> persist selection
//   GET  /fav.ics?u=<uid>                                     -> iCalendar feed
//   GET  /                                                    -> help text
//
// The event *details* live in the bundled programme.js (regenerated by
// build_schedule.py); KV only holds the small per-user id lists.

import { PROGRAMME } from './programme.js';
import { buildIcs } from './ics.mjs';

const MAX_IDS = 2000;                 // generous cap to bound stored payloads
const UID_RE = /^[A-Za-z0-9_-]{8,100}$/;
const ID_RE = /^[a-f0-9]{6,32}$/;     // matches event_dom_id() output
const TTL_SECONDS = 60 * 60 * 24 * 400; // forget inactive users after ~13 months

function cors(extra) {
  return {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    ...(extra || {}),
  };
}

function json(obj, status) {
  return new Response(JSON.stringify(obj), {
    status: status || 200,
    headers: { 'Content-Type': 'application/json; charset=utf-8', ...cors() },
  });
}

function sanitizeIds(arr) {
  if (!Array.isArray(arr)) return [];
  const out = [];
  const seen = new Set();
  for (const x of arr) {
    if (typeof x === 'string' && ID_RE.test(x) && !seen.has(x)) {
      seen.add(x);
      out.push(x);
      if (out.length >= MAX_IDS) break;
    }
  }
  return out;
}

function itemsFor(stored) {
  const favs = (stored && stored.favs) || [];
  const boughtSet = new Set((stored && stored.bought) || []);
  const items = [];
  for (const id of favs) {
    const rec = PROGRAMME[id];
    if (!rec) continue; // event no longer in the programme – skip silently
    items.push({
      id,
      date: rec.d, s: rec.s, e: rec.e,
      title: rec.t || '', venue: rec.v || '', org: rec.o || '',
      cat: rec.c || '', desc: rec.desc || '', ticket: rec.tk || '',
      bought: boughtSet.has(id),
    });
  }
  // Stable chronological order regardless of how the browser sent them.
  items.sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : a.s - b.s));
  return items;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (request.method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: cors() });
    }

    // --- Save a user's selection -----------------------------------------
    if (url.pathname === '/save' && request.method === 'POST') {
      const u = url.searchParams.get('u') || '';
      if (!UID_RE.test(u)) return json({ error: 'bad uid' }, 400);
      let data;
      try { data = await request.json(); } catch (e) { return json({ error: 'bad json' }, 400); }
      const favs = sanitizeIds(data && data.favs);
      const bought = sanitizeIds(data && data.bought);
      if (!env.MV_KV) return json({ error: 'storage not configured' }, 500);
      await env.MV_KV.put(
        'u:' + u,
        JSON.stringify({ favs, bought, t: Date.now() }),
        { expirationTtl: TTL_SECONDS },
      );
      return json({ ok: true, count: favs.length });
    }

    // --- Serve a user's calendar feed ------------------------------------
    if (url.pathname === '/fav.ics' && request.method === 'GET') {
      const u = url.searchParams.get('u') || '';
      if (!UID_RE.test(u)) {
        return new Response('bad uid', { status: 400, headers: cors() });
      }
      let stored = null;
      if (env.MV_KV) {
        const raw = await env.MV_KV.get('u:' + u);
        if (raw) { try { stored = JSON.parse(raw); } catch (e) { stored = null; } }
      }
      const body = buildIcs(itemsFor(stored));
      return new Response(body, {
        status: 200,
        headers: {
          'Content-Type': 'text/calendar; charset=utf-8',
          'Content-Disposition': 'inline; filename="medeltidsveckan-favoriter.ics"',
          'Cache-Control': 'public, max-age=900',
          ...cors(),
        },
      });
    }

    if (url.pathname === '/' && request.method === 'GET') {
      return new Response(
        'Medeltidsveckan – favoritkalender.\n' +
        'Prenumerera på /fav.ics?u=<ditt-id>; webbappen sätter id åt dig.\n',
        { status: 200, headers: { 'Content-Type': 'text/plain; charset=utf-8', ...cors() } },
      );
    }

    return new Response('Not found', { status: 404, headers: cors() });
  },
};
